### PR TITLE
fix issue #14 - force box-sizing content-box for gw-gridline

### PR DESCRIPTION
**Pull request by radum**
This fixes issue #14 where the line height is not properly calculated for
websites where box-sizing is set to border-box for all elements.

### CODE REVIEW

**Comment by itsthatguy** [comment]
@radum Could you recompile the coffeescript using the same amount of spaces?

The javascript diff should be minimal.

**Comment by radum** [comment]
Yeah sorry about that. Done.

**Comment by itsthatguy** [comment]
I'm confused. It looks like the javascript was edited directly, rather than the coffeescript... is that what's going on here?

**Comment by radum** [comment]
Not sure what converter you use, but I use http://js2.coffee/, and that is the result.

Looks ok and works just fine for me.

Also if the main source is in coffee the js output doesn't really matters right?

**Comment by itsthatguy** [comment]
I use the command line coffee compiler... there is a dev-environment branch used for development... I'll loop back around shortly with a more verbose response :)

fwiw, I do want to get your PR in, and give you 100% credit. At the same time, I'd like to avoid a bloated change set.

**Comment by smeranda** [comment]
I'd love to see this get pulled in. Thanks @itsthatguy and @radum!

**Pull request merged**
